CREATE TABLE photos
(id INTEGER PRIMARY KEY,
url TEXT NOT NULL,
site CHARACTER(30) NOT NULL,
coordinates POINT NOT NULL,
radius FLOAT NOT NULL,
photodate DATE NOT NULL,
fhasface BOOLEAN NOT NULL,
mhasface BOOLEAN NOT NULL
);

CREATE TABLE ffaces
(id INTEGER PRIMARY KEY,
url TEXT NOT NULL,
site CHARACTER(30) NOT NULL,
gender INTEGER NOT NULL,
age INTEGER NOT NULL,
race CHARACTER(5) NOT NULL,
smiling FLOAT NOT NULL,
glass FLOAT NOT NULL
);

CREATE TABLE mfaces
(id INTEGER PRIMARY KEY,
url TEXT NOT NULL,
site CHARACTER(30) NOT NULL,
anger FLOAT NOT NULL,
contempt FLOAT NOT NULL,
disgust FLOAT NOT NULL,
fear FLOAT NOT NULL,
happiness FLOAT NOT NULL,
neutral FLOAT NOT NULL,
sadness FLOAT NOT NULL,
surprise FLOAT NOT NULL
)
